// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2tegf_JMvS_v-ZZoH8xuCDVhhEbVwKM',
    appId: '1:674474309531:web:fd6d886ee8ccff28c2533e',
    messagingSenderId: '674474309531',
    projectId: 'buy-and-fly-88c0e',
    authDomain: 'buy-and-fly-88c0e.firebaseapp.com',
    storageBucket: 'buy-and-fly-88c0e.firebasestorage.app',
    measurementId: 'G-BNQX9VKXK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxJyr8athPQj_-X3W5cjKRYTTGdGGn7tc',
    appId: '1:674474309531:android:6ae08510322acb12c2533e',
    messagingSenderId: '674474309531',
    projectId: 'buy-and-fly-88c0e',
    storageBucket: 'buy-and-fly-88c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbhIpwaHN66VfJcE39p-3mwPcbVJYLZ8',
    appId: '1:674474309531:ios:96fccb1750aec287c2533e',
    messagingSenderId: '674474309531',
    projectId: 'buy-and-fly-88c0e',
    storageBucket: 'buy-and-fly-88c0e.firebasestorage.app',
    iosBundleId: 'com.example.gigastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbhIpwaHN66VfJcE39p-3mwPcbVJYLZ8',
    appId: '1:674474309531:ios:96fccb1750aec287c2533e',
    messagingSenderId: '674474309531',
    projectId: 'buy-and-fly-88c0e',
    storageBucket: 'buy-and-fly-88c0e.firebasestorage.app',
    iosBundleId: 'com.example.gigastore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2tegf_JMvS_v-ZZoH8xuCDVhhEbVwKM',
    appId: '1:674474309531:web:ba9c101f4af5691dc2533e',
    messagingSenderId: '674474309531',
    projectId: 'buy-and-fly-88c0e',
    authDomain: 'buy-and-fly-88c0e.firebaseapp.com',
    storageBucket: 'buy-and-fly-88c0e.firebasestorage.app',
    measurementId: 'G-7EKBC7Z7VW',
  );
}
